server:
  port: 8889
spring:
  application:
    name: YUEGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///yuegou-product?serverTimezone=UTC
    username: root
    password: 821096

