server:
  port: 8889
spring:
  application:
    name: YUEGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mybatis?serverTimezone=UTC
    username: root
    password: 821096
mybatis-plus:
  mapper-locations: classpath*:cn/it/yuegou/mapper/*Mapper.xml
