server:
  port: 9999
spring:
  application:
    name: YUEGOU-ZUUL

zuul:
  ignored-services: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: YUEGOU-PLAT
      path: /plat/**
    product:
      serviceId: YUEGOU-PRODUCT
      path: /product/**
    product:
      serviceId: YUEGOU-COMMON
      path: /common/**
  prefix: /services

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000